name: Update Pac-Man Graph

on:
  schedule:
    - cron: '0 0 * * *'  # une fois par jour
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate Pac-Man graph GIF
        uses: tren-chvl/pacman-graph-action@main

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/pacman-contribution-graph.gif
          git commit -m "Update pacman GIF"
          git push
